# Generated by Django 6.0.3 on 2026-03-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireresponse',
            old_name='answer',
            new_name='answers',
        ),
    ]
